"""empty message

Revision ID: 501e3f73df49
Revises: 
Create Date: 2023-07-18 21:08:32.131675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501e3f73df49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_moms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_moms'))
    )
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interests'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('category_mom_id', sa.Integer(), nullable=True),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_mom_id'], ['category_moms.id'], name=op.f('fk_users_category_mom_id_category_moms')),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('fk_users_interest_id_interests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('requesting_user_id', sa.Integer(), nullable=True),
    sa.Column('receiving_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['receiving_user_id'], ['users.id'], name=op.f('fk_friendships_receiving_user_id_users')),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], name=op.f('fk_friendships_requesting_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friendships'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('friendship_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_messages_author_id_users')),
    sa.ForeignKeyConstraint(['friendship_id'], ['friendships.id'], name=op.f('fk_messages_friendship_id_friendships')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('friendships')
    op.drop_table('users')
    op.drop_table('interests')
    op.drop_table('category_moms')
    # ### end Alembic commands ###
