"""models

Revision ID: 726390b52557
Revises: 09d60d6c3215
Create Date: 2023-07-11 15:02:01.933732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726390b52557'
down_revision = '09d60d6c3215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
