"""message

Revision ID: 781dd3facd12
Revises: edc7e8b490a2
Create Date: 2023-07-05 22:48:48.233269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781dd3facd12'
down_revision = 'edc7e8b490a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('requesting_user_id', sa.Integer(), nullable=False),
    sa.Column('receiving_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiving_user_id'], ['users.id'], name=op.f('fk_friendships_receiving_user_id_users')),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], name=op.f('fk_friendships_requesting_user_id_users')),
    sa.PrimaryKeyConstraint('requesting_user_id', 'receiving_user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.drop_table('friendships')
    # ### end Alembic commands ###
