"""models

Revision ID: 7d3c633fe85a
Revises: 134a9184053e
Create Date: 2023-07-06 10:37:06.016504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3c633fe85a'
down_revision = '134a9184053e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendshipstatuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friendship_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['friendship_id'], ['friendships.id'], name=op.f('fk_friendshipstatuses_friendship_id_friendships')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_friendshipstatuses_message_id_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friendshipstatuses'))
    )
    op.drop_table('categories')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_messages_user_id_users', 'users', ['user_id'], ['id'])

    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_categories')
    )
    op.drop_table('friendshipstatuses')
    # ### end Alembic commands ###
