"""message

Revision ID: 88cfcb6b75d2
Revises: 781dd3facd12
Create Date: 2023-07-05 22:55:34.522398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cfcb6b75d2'
down_revision = '781dd3facd12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('requesting_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('receiving_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.alter_column('receiving_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('requesting_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
