"""models update

Revision ID: 927b293673bc
Revises: 7d3c633fe85a
Create Date: 2023-07-07 15:24:45.194683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927b293673bc'
down_revision = '7d3c633fe85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendshipstatuses')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friendship_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_messages_friendship_id_friendships'), 'friendships', ['friendship_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_friendship_id_friendships'), type_='foreignkey')
        batch_op.drop_column('friendship_id')

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('friendshipstatuses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('friendship_id', sa.INTEGER(), nullable=True),
    sa.Column('message_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['friendship_id'], ['friendships.id'], name='fk_friendshipstatuses_friendship_id_friendships'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='fk_friendshipstatuses_message_id_messages'),
    sa.PrimaryKeyConstraint('id', name='pk_friendshipstatuses')
    )
    # ### end Alembic commands ###
