"""models

Revision ID: 97161cb1b1ee
Revises: f5e842bf6251
Create Date: 2023-07-05 16:17:14.032936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97161cb1b1ee'
down_revision = 'f5e842bf6251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requesting_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('receiving_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_friendships_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_friendships_recipient_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_friendships_requesting_user_id_users'), 'users', ['requesting_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_friendships_receiving_user_id_users'), 'users', ['receiving_user_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_messages_friendship_id_friendships', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('friendship_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friendship_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_messages_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_friendship_id_friendships', 'friendships', ['friendship_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_friendships_receiving_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friendships_requesting_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_friendships_recipient_id_users', 'users', ['recipient_id'], ['id'])
        batch_op.create_foreign_key('fk_friendships_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('receiving_user_id')
        batch_op.drop_column('requesting_user_id')

    # ### end Alembic commands ###
