"""message

Revision ID: 9ddb99bfed9a
Revises: b63dd4cb0091
Create Date: 2023-07-05 21:23:02.620462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddb99bfed9a'
down_revision = 'b63dd4cb0091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_interest_id_interests'), 'interests', ['interest_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_interest_id_interests'), type_='foreignkey')
        batch_op.drop_column('interest_id')

    # ### end Alembic commands ###
