"""message

Revision ID: b63dd4cb0091
Revises: 97161cb1b1ee
Create Date: 2023-07-05 21:17:02.611369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63dd4cb0091'
down_revision = '97161cb1b1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_moms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_moms_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_interests_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_mom_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_category_mom_id_category_moms'), 'category_moms', ['category_mom_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_category_mom_id_category_moms'), type_='foreignkey')
        batch_op.drop_column('category_mom_id')

    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_interests_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('category_moms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_category_moms_user_id_users', 'users', ['user_id'], ['id'])

    op.drop_table('categories')
    # ### end Alembic commands ###
