"""models

Revision ID: edc7e8b490a2
Revises: 9ddb99bfed9a
Create Date: 2023-07-05 21:28:01.610396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc7e8b490a2'
down_revision = '9ddb99bfed9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('requesting_user_id', sa.INTEGER(), nullable=False),
    sa.Column('receiving_user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['receiving_user_id'], ['users.id'], name='fk_friendships_receiving_user_id_users'),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], name='fk_friendships_requesting_user_id_users')
    )
    # ### end Alembic commands ###
